# Este é um fluxo de trabalho básico para ajudá-lo a começar com Actions

name: CI

# Controla quando o fluxo de trabalho será executado
on:
  # Dispara o fluxo de trabalho em eventos de push ou pull request, mas apenas para o branch "main"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Permite que você execute este fluxo de trabalho manualmente na guia Actions
  workflow_dispatch:

# Um fluxo de trabalho é composto por um ou mais jobs que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único job chamado "build"
  build:
    # O tipo de runner que o job executará
    runs-on: ubuntu-latest

    # Etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      # Verifica o seu repositório em $GITHUB_WORKSPACE, para que seu job possa acessá-lo
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          ref: main
      
      # Executa um conjunto de comandos usando o shell do runner
      - name: Verificar versão do Newman e Node
        run: |
          newman --version
          node --version
          
      # Executa um único comando usando o shell do runner      
      - name: Instalar Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
      
      # Executa um conjunto de comandos usando o shell do runner
      - name: Executar coleção
        run: newman run ./reqRes-api.json -e ./reqRes.env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
   
      # Executa um conjunto de comandos usando o shell do runner
      - name: Arquivar artefatos de produção
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
