name: Req Res

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      # Instala e configura o Node.js 20
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Verifica as versões do Newman e do Node.js
      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version
          
      # Instala o Newman-Reporter-Htmlextra
      - name: Step 2 Install Newman-Reporter-Htmlextra
        run: npm install -g newman-reporter-htmlextra
        
      # Executa a coleção com Newman
      - name: Step 3 Execute collection
        run: newman run ./reqRes-api.json -e ./reqRes.env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
   
      # Arquiva os artefatos de produção
      - name: Step 4 Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
            name: report
            path: ./results/Report.html
