name: Testes com Postman

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # escolha a versão desejada do Node.js

    - name: Instalar dependências
      run: npm install newman

    - name: Executar testes com Postman
      run: |
        newman run ./reqRes-api.json -e ./reqRes.env.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./results/Report.html
