name: Teste Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Executar testes do Postman
        run: bash run_tests.sh

      - name: Arquivar resultados
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./results
