name: Teste Postman

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install -g newman newman-reporter-htmlextra

      - name: Executar testes do Postman
        run: newman run ./reqRes-api.json -e ./reqRes.env.json --reporters cli,htmlextra --reporter-htmlextra-export ./results/Report.html

      - name: Arquivar resultados
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./results
